import { Colaborador } from "../interfaces/colaboradores";

export const LIST_COLABORADORES: Colaborador[] = [
  {
    personaId: 15,
    colaboradorId: 1,
    nombre: "Felecia",
    apellido: "Hatrick",
    dni: " 18418268",
    telefono: "5966858270",
    email: "fhatrick0@indiatimes.com",
    usuario: "fhatrick0",
    clave: "gE7{H",
  },
  {
    personaId: 12,
    colaboradorId: 2,
    nombre: "Alard",
    apellido: "Gerard",
    dni: " 170050",
    telefono: "6833692325",
    email: "agerard1@yahoo.com",
    usuario: "agerard1",
    clave: "dS2_'Ad",
  },
  {
    personaId: 10,
    colaboradorId: 3,
    nombre: "Wilburt",
    apellido: "Murrell",
    dni: " 24645368",
    telefono: "2609312895",
    email: "wmurrell2@geocities.com",
    usuario: "wmurrell2",
    clave: "xX1)'",
  },
  {
    personaId: 14,
    colaboradorId: 4,
    nombre: "Belicia",
    apellido: "Aucutt",
    dni: " 1517195",
    telefono: "2325172266",
    email: "baucutt3@booking.com",
    usuario: "baucutt3",
    clave: "zO5?X",
  },
  {
    personaId: 19,
    colaboradorId: 5,
    nombre: "Lucille",
    apellido: "Speers",
    dni: " 14779947",
    telefono: "6941747795",
    email: "lspeers4@ucsd.edu",
    usuario: "lspeers4",
    clave: "eQ6=e5w_",
  },
  {
    personaId: 17,
    colaboradorId: 6,
    nombre: "Marten",
    apellido: "Dreinan",
    dni: " 90731878",
    telefono: "6092200703",
    email: "mdreinan5@tuttocitta.it",
    usuario: "mdreinan5",
    clave: "wB7'i",
  },
  {
    personaId: 18,
    colaboradorId: 7,
    nombre: "Liz",
    apellido: "Tuckett",
    dni: " 31981649",
    telefono: "2472262337",
    email: "ltuckett6@google.com.br",
    usuario: "ltuckett6",
    clave: "nX2|jr87",
  },
  {
    personaId: 16,
    colaboradorId: 8,
    nombre: "Egor",
    apellido: "Zanneli",
    dni: " 44135922",
    telefono: "6432863161",
    email: "ezanneli7@wordpress.org",
    usuario: "ezanneli7",
    clave: "iS5@d",
  },
  {
    personaId: 20,
    colaboradorId: 9,
    nombre: "Sharron",
    apellido: "Paddefield",
    dni: " 63877279",
    telefono: "8056602219",
    email: "spaddefield8@smh.com.au",
    usuario: "spaddefield8",
    clave: "aH0,I'F%",
  },
  {
    personaId: 11,
    colaboradorId: 13,
    nombre: "Crista",
    apellido: "Grammer",
    dni: " 32749239",
    telefono: "8168726053",
    email: "cgrammer9@google.co.uk",
    usuario: "cgrammer9",
    clave: "eJ1>V0FT",
  },
];
