import { TurnoInterface } from "../interfaces/turno";

export const LIST_TURNOS: TurnoInterface[] = [
    {
        id: "1",
        dia: "2025-01-26",
        hora: "09:30",
        duracion: "30",
        estado: true,
        paciente: {
            id: 1,
            nombre: "Laureano ivan",
            apellido: "luna",
            dni: "38232325",
            email: "laureano@luna.com",
            direccion: "nahuel 696",
            fechaNac: new Date("19940622"),
            telefono: "12345678910",
            consentimiento: { tiene: false },
        },
    },
    {
        id: "2",
        dia: "2025-01-29",
        hora: "19:30",
        duracion: "30",
        estado: true,
        paciente: {
            id: 1,
            nombre: "Laureano ivan",
            apellido: "luna",
            dni: "38232325",
            email: "laureano@luna.com",
            direccion: "nahuel 696",
            fechaNac: new Date("19940622"),
            telefono: "12345678910",
            consentimiento: { tiene: false },
        },
    },
    {
        id: "3",
        dia: "2025-01-24",
        hora: "20:30",
        duracion: "30",
        estado: true,
        paciente: {
            id: 1,
            nombre: "Laureano ivan",
            apellido: "luna",
            dni: "38232325",
            email: "laureano@luna.com",
            direccion: "nahuel 696",
            fechaNac: new Date("19940622"),
            telefono: "12345678910",
            consentimiento: { tiene: false },
        },
    },
    {
        id: "4",
        dia: "2025-01-24",
        hora: "19:30",
        duracion: "30",
        estado: true,
        paciente: {
            id: 1,
            nombre: "Laureano ivan",
            apellido: "luna",
            dni: "38232325",
            email: "laureano@luna.com",
            direccion: "nahuel 696",
            fechaNac: new Date("19940622"),
            telefono: "12345678910",
            consentimiento: { tiene: false },
        },
    },
    {
        id: "5",
        dia: "2025-01-26",
        hora: "19:30",
        duracion: "30",
        estado: true,
        paciente: {
            id: 1,
            nombre: "Laureano ivan",
            apellido: "luna",
            dni: "38232325",
            email: "laureano@luna.com",
            direccion: "nahuel 696",
            fechaNac: new Date("19940622"),
            telefono: "12345678910",
            consentimiento: { tiene: false },
        },
    },
    {
        id: "6",
        dia: "2025-01-30",
        hora: "15:30",
        duracion: "30",
        estado: true,
        paciente: {
            id: 1,
            nombre: "Laureano ivan",
            apellido: "luna",
            dni: "38232325",
            email: "laureano@luna.com",
            direccion: "nahuel 696",
            fechaNac: new Date("19940622"),
            telefono: "12345678910",
            consentimiento: { tiene: false },
        },
    },
];