import { Zona } from "../interfaces/zona";

export const LIST_ZONAS: Zona[] = [
  {
    zonaId: 21,
    codigoZona: "BR-XY",
    nombre: "Cetirizine",
    descripcion: "",
    precio: 2899.99,
    tiempo: 15,
    deshabilitado: false,
    sexo: "H",
    tamaño: "G",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 22,
    codigoZona: "MM-02",
    nombre: "Echinacea Purpurea",
    precio: 4321.50,
    descripcion: "",
    tiempo: 10,
    deshabilitado: true,
    sexo: "M",
    tamaño: "M",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 23,
    codigoZona: "FI-RT",
    nombre: "Bacopa Monnieri",
    descripcion: "",
    precio: 1500.75,
    tiempo: 20,
    deshabilitado: false,
    sexo: "H",
    tamaño: "M",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 24,
    codigoZona: "US-NY",
    nombre: "Ginkgo Biloba",
    descripcion: "",
    precio: 7645.22,
    tiempo: 30,
    deshabilitado: true,
    sexo: "M",
    tamaño: "C",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 25,
    codigoZona: "ES-BC",
    nombre: "Omega 3 Fish Oil",
    descripcion: "",
    precio: 5120.88,
    tiempo: 12,
    deshabilitado: false,
    sexo: "H",
    tamaño: "C",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 26,
    codigoZona: "VE-GH",
    nombre: "L-Theanine",
    precio: 6789.45,
    tiempo: 25,
    descripcion: "",
    deshabilitado: false,
    sexo: "M",
    tamaño: "M",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 27,
    codigoZona: "GB-UK",
    nombre: "Melatonin",
    precio: 3456.78,
    descripcion: "",
    tiempo: 8,
    deshabilitado: false,
    sexo: "H",
    tamaño: "G",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 28,
    codigoZona: "US-TX",
    nombre: "Probiotics",
    precio: 4999.99,
    tiempo: 14,
    deshabilitado: false,
    sexo: "M",
    tamaño: "G",
    descripcion: "",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 29,
    codigoZona: "CA-ON",
    nombre: "Vitamin D3",
    precio: 2399.50,
    tiempo: 18,
    deshabilitado: false,
    sexo: "H",
    tamaño: "G",
    descripcion: "",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 30,
    codigoZona: "GA-5",
    nombre: "Turmeric Curcumin",
    precio: 4100.00,
    tiempo: 9,
    deshabilitado: false,
    sexo: "M",
    descripcion: "",
    tamaño: "M",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 31,
    codigoZona: "ZM-09",
    nombre: "Zinc Picolinate",
    precio: 1599.99,
    tiempo: 11,
    deshabilitado: false,
    descripcion: "",
    sexo: "H",
    tamaño: "C",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 32,
    codigoZona: "US-NJ",
    nombre: "CoQ10",
    precio: 3250.75,
    tiempo: 7,
    deshabilitado: true,
    sexo: "H",
    descripcion: "",
    tamaño: "C",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 33,
    codigoZona: "US-OR",
    nombre: "Ginseng",
    precio: 6700.00,
    tiempo: 16,
    deshabilitado: false,
    sexo: "M",
    tamaño: "G",
    descripcion: "",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 34,
    codigoZona: "GE-TX",
    nombre: "Ashwagandha",
    precio: 7890.99,
    tiempo: 19,
    deshabilitado: false,
    sexo: "H",
    descripcion: "",
    tamaño: "G",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 35,
    codigoZona: "ID-CA",
    nombre: "Spirulina",
    precio: 4550.50,
    tiempo: 22,
    deshabilitado: false,
    sexo: "H",
    descripcion: "",
    tamaño: "G",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 36,
    codigoZona: "CA-QC",
    nombre: "Fiber Supplements",
    precio: 2780.00,
    tiempo: 5,
    deshabilitado: false,
    sexo: "M",
    descripcion: "",
    tamaño: "M",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 37,
    codigoZona: "AU-NSW",
    nombre: "Electrolyte Powder",
    precio: 3100.00,
    tiempo: 4,
    descripcion: "",
    deshabilitado: false,
    sexo: "H",
    tamaño: "C",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 38,
    codigoZona: "CA-AB",
    nombre: "Collagen Peptides",
    precio: 5400.00,
    tiempo: 13,
    deshabilitado: false,
    sexo: "H",
    descripcion: "",
    tamaño: "C",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 39,
    codigoZona: "PG-XYZ",
    nombre: "Kava Kava",
    precio: 4200.00,
    tiempo: 8,
    deshabilitado: false,
    descripcion: "",
    sexo: "H",
    tamaño: "M",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
  {
    zonaId: 40,
    codigoZona: "US-WA",
    nombre: "Chia Seeds",
    precio: 1999.99,
    tiempo: 14,
    descripcion: "",
    deshabilitado: false,
    sexo: "M",
    tamaño: "G",
    tipoZona: {
      tipoZonaId: 2,
      descripcion: "",
      tipoZona: "Tipo 2",
      deshabilitado: false,
    },
  },
];