import { Zona } from "../interfaces/zona";

export const LIST_ZONAS: Zona[] = [
  {
    "zonaId": 1,
    "tipo": "C",
    "codigo": "C001",
    "nombre": "Zona de Aventura",
    "descripcion": "Área destinada a actividades de aventura al aire libre.",
    "precio": 250.00,
    "tiempo": 120,
    "deshabilitado": false,
    "sexo": "M",
    "tamaño": "Grande",
    "zonaPadreId": undefined
  },
  {
    "zonaId": 2,
    "tipo": "Z",
    "codigo": "Z002",
    "nombre": "Zona de Estudio",
    "descripcion": "Espacio tranquilo para el estudio y la concentración.",
    "precio": 100.00,
    "tiempo": 60,
    "deshabilitado": false,
    "sexo": "H",
    "tamaño": "Pequeño",
    "zonaPadreId": 1
  },
  {
    "zonaId": 3,
    "tipo": "C",
    "codigo": "C003",
    "nombre": "Zona de Juegos",
    "descripcion": "Área destinada para juegos infantiles y actividades recreativas.",
    "precio": 80.00,
    "tiempo": 30,
    "deshabilitado": false,
    "sexo": "M",
    "tamaño": "Mediano",
    "zonaPadreId": 1
  },
  {
    "zonaId": 4,
    "tipo": "Z",
    "codigo": "Z004",
    "nombre": "Zona de Relajación",
    "descripcion": "Espacio para la relajación, meditación y descanso.",
    "precio": 120.00,
    "tiempo": 45,
    "deshabilitado": true,
    "sexo": "H",
    "tamaño": "Grande",
    "zonaPadreId": undefined
  },
  {
    "zonaId": 5,
    "tipo": "C",
    "codigo": "C005",
    "nombre": "Zona de Fitness",
    "descripcion": "Área equipada para hacer ejercicio y actividades físicas.",
    "precio": 200.00,
    "tiempo": 90,
    "deshabilitado": false,
    "sexo": "M",
    "tamaño": "Grande",
    "zonaPadreId": undefined
  },
  {
    "zonaId": 6,
    "tipo": "Z",
    "codigo": "Z006",
    "nombre": "Zona de Eventos",
    "descripcion": "Espacio para la realización de eventos, conferencias y reuniones.",
    "precio": 300.00,
    "tiempo": 180,
    "deshabilitado": false,
    "sexo": "H",
    "tamaño": "Muy Grande",
    "zonaPadreId": undefined
  },
  {
    "zonaId": 7,
    "tipo": "C",
    "codigo": "C007",
    "nombre": "Zona de Comida",
    "descripcion": "Área con opciones de comida y bebida para los visitantes.",
    "precio": 50.00,
    "tiempo": 60,
    "deshabilitado": false,
    "sexo": "M",
    "tamaño": "Pequeño",
    "zonaPadreId": 5
  },
  {
    "zonaId": 8,
    "tipo": "Z",
    "codigo": "Z008",
    "nombre": "Zona de Arte",
    "descripcion": "Espacio dedicado a actividades artísticas, exposiciones y talleres.",
    "precio": 90.00,
    "tiempo": 120,
    "deshabilitado": false,
    "sexo": "H",
    "tamaño": "Mediano",
    "zonaPadreId": 6
  },
  {
    "zonaId": 9,
    "tipo": "C",
    "codigo": "C009",
    "nombre": "Zona de Mascotas",
    "descripcion": "Área donde se permite la entrada de mascotas y actividades relacionadas.",
    "precio": 70.00,
    "tiempo": 30,
    "deshabilitado": false,
    "sexo": "M",
    "tamaño": "Pequeño",
    "zonaPadreId": undefined
  },
  {
    "zonaId": 10,
    "tipo": "Z",
    "codigo": "Z010",
    "nombre": "Zona de Tecnología",
    "descripcion": "Espacio equipado con tecnología avanzada para actividades interactivas.",
    "precio": 250.00,
    "tiempo": 150,
    "deshabilitado": false,
    "sexo": "H",
    "tamaño": "Grande",
    "zonaPadreId": 6
  }
];